# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96162e70b56ba3220ad48bcea4a1a74bc9145b166a34bf21eb96dbd2fa88d5215780c7b73a38684407c0e698e5141a5f6953883eae8987fc08336e49a246d22b

test:
  secret_key_base: 43e870591f20421007bf0c6dbfed2ec481bbefee77698706c123e8222a9df7d24c5c4369680d637bcfab4faa8bf07e564fddc8ad3993c47e68fcd9c874229553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
